const assert=require('node:assert/strict');
const {classify,summary}=require('../android/assets/cleanup.js');
const now=1800000000000,D=86400000;
const file=(over={})=>({id:'a',name:'family.jpg',path:'DCIM / Camera',size:100,date:now-90*D,...over});
const keys=f=>classify(f,now).map(r=>r.key);
assert.deepEqual(keys(file()),[],'Old user photo must not become junk');
assert.deepEqual(keys(file({name:'notes.pdf'})),[],'Old document must not become junk');
assert.deepEqual(keys(file({name:'a.tmp',date:now-2*D})),[],'Recent temporary file excluded');
assert.deepEqual(keys(file({name:'a.tmp',date:0})),[],'Unknown timestamp excluded from aged rules');
assert.deepEqual(keys(file({name:'a.tmp',date:now+D})),[],'Future timestamp excluded');
assert(keys(file({name:'a.tmp',date:now-7*D})).includes('temp'));
assert(keys(file({path:'Telegram / cache'})).includes('temp'));
assert(!keys(file({path:'Telegram / cache-backup'})).includes('temp'),'No broad substring matching');
assert(keys(file({path:'Pictures / clipboard'})).includes('clipboard'));
assert(!keys(file({name:'clipboard.jpg',path:'DCIM'})).includes('clipboard'));
assert(keys(file({name:'setup.apk'})).includes('installer'));
assert.deepEqual(keys(file({packageName:'com.test.app',packageState:'installed'})),[],'Installed App never residual');
assert(keys(file({packageName:'com.test.app',packageState:'unknown'})).includes('residual'));
assert(keys(file({size:0})).includes('empty'));
assert.deepEqual(keys(file({size:200*1048576})),['large']);
const overlap=file({name:'a.tmp',path:'Pictures / clipboard',size:200});
const report=summary([overlap,file({id:'b',size:200*1048576})],now);
assert.equal(report.candidates.length,1);assert.equal(report.bytes,200,'Candidate totals deduplicate categories and exclude large-only files');
console.log('PASS: 16 checks for age gates, preserved photos/documents, no substring overmatch, package status, zero-byte files, large files and deduplicated totals.');
